# Generated by Django 5.2.12 on 2026-04-05 08:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='offline', max_length=16)),
                ('last_seen_ms', models.BigIntegerField(blank=True, null=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='monitoring.bed')),
            ],
            options={
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('doctor', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_nurse', models.CharField(blank=True, default='', max_length=255)),
                ('device_battery', models.FloatField(default=100.0)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hr', models.PositiveIntegerField(default=75)),
                ('spo2', models.PositiveIntegerField(default=98)),
                ('nibp_sys', models.PositiveIntegerField(default=120)),
                ('nibp_dia', models.PositiveIntegerField(default=80)),
                ('rr', models.PositiveIntegerField(default=16)),
                ('temp', models.FloatField(default=36.6)),
                ('nibp_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('alarm_level', models.CharField(choices=[('none', 'none'), ('blue', 'blue'), ('yellow', 'yellow'), ('red', 'red'), ('purple', 'purple')], default='none', max_length=16)),
                ('alarm_message', models.TextField(blank=True, default='')),
                ('alarm_limits', models.JSONField(default=dict)),
                ('scheduled_check', models.JSONField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('news2_score', models.PositiveSmallIntegerField(default=0)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='monitoring.bed')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dose', models.CharField(blank=True, default='', max_length=255)),
                ('rate', models.CharField(blank=True, default='', max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='monitoring.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=64)),
                ('unit', models.CharField(blank=True, default='', max_length=64)),
                ('time_ms', models.BigIntegerField()),
                ('is_abnormal', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='monitoring.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('time_ms', models.BigIntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='monitoring.patient')),
            ],
            options={
                'ordering': ['-time_ms'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='monitoring.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='monitoring.room'),
        ),
        migrations.CreateModel(
            name='VitalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_ms', models.BigIntegerField(db_index=True)),
                ('hr', models.FloatField()),
                ('spo2', models.FloatField()),
                ('nibp_sys', models.FloatField()),
                ('nibp_dia', models.FloatField()),
                ('rr', models.FloatField()),
                ('temp', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_rows', to='monitoring.patient')),
            ],
            options={
                'ordering': ['timestamp_ms'],
                'indexes': [models.Index(fields=['patient', 'timestamp_ms'], name='monitoring__patient_dee933_idx')],
            },
        ),
    ]
