# Generated by Django 5.0.1 on 2026-04-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hl7_sending_application',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
